version: '2'
services:
  pgsql:
    build: ./pgsql/
    container_name: aeternity-tokes-pgsql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
  csv-generator:
    environment:
      - POSTGRES_HOST=pgsql
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - ETHERSCAN_API_TOKEN=${ETHERSCAN_API_TOKEN}
    build: .
    container_name: csv-generator
    tty: true
    restart: always
    depends_on:
      - pgsql
